-- Migration: add missing columns for form payloads
-- Date: 2026-02-20
-- Note: quoted identifiers preserve camelCase to match current form field names.

-- ELEITORES
ALTER TABLE eleitores
  ADD COLUMN IF NOT EXISTS "tituloEleitoral" VARCHAR(12),
  ADD COLUMN IF NOT EXISTS "secao" VARCHAR(10),
  ADD COLUMN IF NOT EXISTS "zona" VARCHAR(10),
  ADD COLUMN IF NOT EXISTS "municipio" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "situacaoTSE" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "localVotacao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "biometria" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "nomeSocial" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "rg" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "nomePai" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "nomeMae" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "naturalidade" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "estadoCivil" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "localTrabalho" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT,
  ADD COLUMN IF NOT EXISTS "celular" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "whatsapp" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "logradouro" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "uf" VARCHAR(2),
  ADD COLUMN IF NOT EXISTS "dataNascimento" DATE,
  ADD COLUMN IF NOT EXISTS "statusCadastro" VARCHAR(50);

ALTER TABLE eleitores
  ALTER COLUMN sexo TYPE VARCHAR(20);

-- LIDERANCAS
ALTER TABLE liderancas
  ADD COLUMN IF NOT EXISTS "rg" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "dataNascimento" DATE,
  ADD COLUMN IF NOT EXISTS "sexo" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "nomePai" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "nomeMae" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "naturalidade" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "estadoCivil" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "profissao" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "logradouro" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "complemento" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "uf" VARCHAR(2),
  ADD COLUMN IF NOT EXISTS "areaAtuacao" VARCHAR(255);

-- FUNCIONARIOS
ALTER TABLE funcionarios
  ADD COLUMN IF NOT EXISTS "rg" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "sexo" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "nomePai" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "nomeMae" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "naturalidade" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "estadoCivil" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "logradouro" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "complemento" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "uf" VARCHAR(2),
  ADD COLUMN IF NOT EXISTS "dataNascimento" DATE,
  ADD COLUMN IF NOT EXISTS "dataAdmissao" DATE,
  ADD COLUMN IF NOT EXISTS "cargaHoraria" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "tipoContrato" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "matricula" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "pis" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "ctps" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "banco" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "agencia" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "conta" VARCHAR(30),
  ADD COLUMN IF NOT EXISTS "tipoConta" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "pix" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT;

-- ATENDIMENTOS
ALTER TABLE atendimentos
  ADD COLUMN IF NOT EXISTS "tipoAtendimento" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "liderancaResponsavel" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "localidadeAtendida" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "servicosOferecidos" TEXT,
  ADD COLUMN IF NOT EXISTS "eleitorCpf" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "eleitorNome" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "eleitorEmail" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "eleitorCelular" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "tipoEspecifico" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "descricaoDocumento" TEXT,
  ADD COLUMN IF NOT EXISTS "encaminhamento" TEXT,
  ADD COLUMN IF NOT EXISTS "tipoAtendimentoJuridico" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "agendamento" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "statusAtendimento" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "dataAtendimento" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "dataConclusao" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT,
  ADD COLUMN IF NOT EXISTS "notificarEleitor" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "modoNotificacao" VARCHAR(20);

-- AGENDA_EVENTOS
ALTER TABLE agenda_eventos
  ADD COLUMN IF NOT EXISTS "horaInicio" TIME,
  ADD COLUMN IF NOT EXISTS "horaFim" TIME,
  ADD COLUMN IF NOT EXISTS "endereco" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "permitirConfirmacao" BOOLEAN DEFAULT true;

-- SOLICITACOES
ALTER TABLE solicitacoes
  ADD COLUMN IF NOT EXISTS "telefone" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "email" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "documentos" JSONB,
  ADD COLUMN IF NOT EXISTS "tipoSolicitante" VARCHAR(50);

-- EMENDAS
ALTER TABLE emendas
  ADD COLUMN IF NOT EXISTS "numero" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "tipo" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "autor" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "orgao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "responsavel" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "finalidade" TEXT,
  ADD COLUMN IF NOT EXISTS "valorEmpenhado" NUMERIC(15, 2),
  ADD COLUMN IF NOT EXISTS "valorExecutado" NUMERIC(15, 2),
  ADD COLUMN IF NOT EXISTS "dataEmpenho" DATE,
  ADD COLUMN IF NOT EXISTS "dataVencimento" DATE,
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT;

-- REPASSES
ALTER TABLE repasses
  ADD COLUMN IF NOT EXISTS "codigo" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "emenda" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "parcela" INTEGER,
  ADD COLUMN IF NOT EXISTS "totalParcelas" INTEGER,
  ADD COLUMN IF NOT EXISTS "dataPrevista" DATE,
  ADD COLUMN IF NOT EXISTS "dataEfetivada" DATE,
  ADD COLUMN IF NOT EXISTS "orgao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "responsavel" VARCHAR(255);

-- ORGAOS
ALTER TABLE orgaos
  ADD COLUMN IF NOT EXISTS "codigo" INTEGER,
  ADD COLUMN IF NOT EXISTS "tipo" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "cnpj" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "municipio" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "uf" VARCHAR(2),
  ADD COLUMN IF NOT EXISTS "contato" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT;

-- RESPONSAVEIS_EMENDAS
ALTER TABLE responsaveis_emendas
  ADD COLUMN IF NOT EXISTS "nome" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "cargo" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "orgao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "cpf" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "telefone" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "email" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "whatsapp" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT,
  ADD COLUMN IF NOT EXISTS "status" VARCHAR(50);

-- USUARIOS (avoid storing password fields; add only non-sensitive form fields)
ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS "liderancaVinculada" BIGINT;
